# gpt-3.5-turbo-0613:
#   import: "./mac_server.yaml"
#   parameters:
#     name: "qwen3:1.7b"
#     body:
#       model: "qwen3:1.7b"
#       max_tokens: 512

qwen3-1.7b:
  import: "./langchain_agent.yaml"
  parameters:
    name: "qwen3:1.7b"
    body:
      model: "qwen3:1.7b"
      max_tokens: 512

qwen2.5-coder:1.5b:
  import: "./langchain_agent.yaml"
  parameters:
    name: "qwen2.5-coder:1.5b"
    body:
      model: "qwen2.5-coder:1.5b"
      max_tokens: 512

qwen3-ollama:
  import: "./ollama.yaml"
  parameters:
    name: "qwen3-direct"
    body:
      model: "qwen3:1.7b"
      max_tokens: 512
